### ISSUE TITLE
Firefox blocks mixed content (comments can't show up by default)

### ISSUE THREAD

**Issue by ylluminarious** [equestriadaily/equestriadaily.github.io#2]
I'm not sure about other browsers, but Firefox Quantum blocks mixed content. This means that the comments won't load since the script is fetched via HTTP.  The only way around this right now is to go into `about:config` and set `security.mixed_content.block_active_content` to `false`. Perhaps the script should be fetched via HTTPS instead to placate modern browsers?

**Comment by leonluc-dev** [comment]
Thanks for the report. The script was fetched over http but due to the way Blogger handled it's URLs. The issue should have been fixed now.

**Comment by ylluminarious** [comment]
@gameleon-dev Thanks, that did the trick!
